# Generated by Django 4.2 on 2023-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='lens_name',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
