# Generated by Django 4.2 on 2023-05-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0004_lens_photo_lens_name_alter_photo_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lens',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='lens_name',
        ),
    ]
