# Generated by Django 4.2 on 2023-05-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0005_delete_lens_remove_photo_lens_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'lenses',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='lens_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_site.lens'),
        ),
    ]
