# Generated by Django 4.2 on 2023-05-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0006_lens_photo_lens_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='lens',
        ),
    ]
