# Generated by Django 4.2 on 2023-05-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_site', '0007_remove_photo_lens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
